# writing excel workbooks
# the instructions use deprecated function names for openpyxl. those
# have been corrected below

import os, openpyxl

# create new excel workbook by calling Workbook function
wb = openpyxl.Workbook()

print(wb.sheetnames)

sheet = wb['Sheet']

print(sheet)

# should have None value because it's a brand new wb with nothing in it
print(sheet['A1'].value)

# update a cell within an assignment statement - this value would exist
# in Python's memory only, not on the hard drive
sheet['A1'] = 'Hello!' 

# now saving workbook to hard drive
wb.save('example.xslx')

# you can also chdir and save in a different directory
os.chdir('/Users/mdf594/desktop')
wb.save('example.xslx')

# changing directory back
os.chdir('/Users/mdf594/desktop/automate')

# if opening existing spreadsheet to modify, save as new file to avoid buggy mistakes
# to do so, use openpyxl.load_workbook('workbook_name')

# you can add new sheets to your Excel file
#sheet2 = wb.create_sheet() will save it awith autogenerated title
sheet2 = wb.create_sheet('Sheet 2') 
print(wb.sheetnames)

# changing a sheet name
sheet2.title = 'New Title'
print(wb.sheetnames)

wb.save('example2.xslx')

# add new sheet to a different position

wb.create_sheet(index=0, title='Index 0 Sheet')
print(wb.sheetnames)
wb.save('example3.xslx')
